include:
  - project: 4s1/gitlab-ci-config
    file: 'all/prevent-detached-pipeline/.gitlab-ci.yml'
  - project: 4s1/gitlab-ci-config
    file: 'typescript/validate/.gitlab-ci.yml'
  - project: 4s1/gitlab-ci-config
    file: 'typescript/sonarlint/.gitlab-ci.yml'

stages:
  - validate
  - sonarlint


validate-job:
  image: registry.gitlab.com/4s1/docker/node:14-buster-dev
