include:
  - project: 4s1/gitlab-ci-config
    file: 'all/.gitlab-ci.yml'
  - project: 4s1/gitlab-ci-config
    file: 'validate-typescript/.gitlab-ci.yml'
  - project: 4s1/gitlab-ci-config
    file: 'sonar-typescript/.gitlab-ci.yml'

stages:
  - validate
  - sonar

validate-job:
  image: registry.gitlab.com/4s1/docker/node:14-buster-dev
