stages:
  - validate

validate-job:
  stage: validate
  # buster is required for canvas
  image: registry.gitlab.com/4s1/docker/node:14-buster-dev
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .pnpm-store
  before_script:
    - pnpm config set store-dir .pnpm-store
    - echo "//gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
  script:
    - pnpm i
    - pnpm run lint
    - pnpm run build
    - pnpm run test
