stages:
  - validating
  - deploying

validate:
  stage: validating
  # buster is required for canvas
  image: registry.gitlab.com/yellowgarbagegroup/docker-images/node:14-buster
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .pnpm-store
  script:
    - npm i pnpm -g
    - pnpm i
    - pnpm run lint
    - pnpm run build
    - pnpm run test

publish:
  stage: deploying
  # buster is required for canvas
  image: registry.gitlab.com/yellowgarbagegroup/docker-images/node:14-buster
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .pnpm-store
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    NPM_TOKEN: ${CI_JOB_TOKEN}
  before_script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
  script:
    - pnpm i
    - pnpm run build
    - pnpm run semantic-release
